name: Quay Management
on:
  push:
    paths:
      - "ansible/**"
    branches:
      - "main"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 3 * * *"

# Declare default permissions as read only.
permissions: read-all

jobs:
  quay-management:
    name: "Quay Organization Management"
    if: "github.repository == 'redhat-cop/org'"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run ansible-lint
        uses: ansible/ansible-lint@c16f018b1bdfdea6717f4b5b1b141a78b86021cd # v25.2.1

      - name: Install Dependencies
        run: ansible-galaxy install -r ansible/requirements.yml -p $HOME/roles

      - name: Manage Quay Repository
        if: github.event_name == 'push' || github.event_name == 'schedule'
        env:
          ANSIBLE_ROLES_PATH: '$HOME/roles/infra-ansible/roles/scm'
        run: ansible-playbook -i ansible/inventory ansible/playbooks/quay_management.yml ${{secrets.ANSIBLE_EXTRA_VARS}}
