name: Update GitHub Org Configuration
on:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - "config.yaml"
    branches:
      - main

# Declare default permissions as read only.
permissions: read-all

jobs:
  manage-github-org-config-workflow:
    name: manage-github-org-config-workflow
    if: "github.repository == 'redhat-cop/org'"
    uses: redhat-cop/org/.github/workflows/manage-github-org.yml@main
    secrets:
      PERIBOLOS_TOKEN: ${{ secrets.PERIBOLOS_TOKEN }}
      PKG_DEV_KEY: ${{ secrets.PKG_DEV_KEY }}
    with:
      APPLY_CHANGES: true
